// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9eHpo7HWB9hCgXdnF1Y40ye4_JxxPNzo',
    appId: '1:466055219719:web:bdca39419ee2e2b5f3b8a2',
    messagingSenderId: '466055219719',
    projectId: 'catering-service-a5641',
    authDomain: 'catering-service-a5641.firebaseapp.com',
    storageBucket: 'catering-service-a5641.appspot.com',
    measurementId: 'G-6QHLBFHQ6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_mr334m3KXhfKQD_FrZNnSQLQeK7nnM',
    appId: '1:466055219719:android:7d29f98e7becffe5f3b8a2',
    messagingSenderId: '466055219719',
    projectId: 'catering-service-a5641',
    storageBucket: 'catering-service-a5641.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwZiuSO6qJfPBNPItPs9kVl4dUJWo9j0',
    appId: '1:466055219719:ios:86f75c86529e8e1ef3b8a2',
    messagingSenderId: '466055219719',
    projectId: 'catering-service-a5641',
    storageBucket: 'catering-service-a5641.appspot.com',
    iosBundleId: 'com.example.eCataring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmwZiuSO6qJfPBNPItPs9kVl4dUJWo9j0',
    appId: '1:466055219719:ios:b4803101c91e5228f3b8a2',
    messagingSenderId: '466055219719',
    projectId: 'catering-service-a5641',
    storageBucket: 'catering-service-a5641.appspot.com',
    iosBundleId: 'com.example.eCataring.RunnerTests',
  );
}
